jwt:
  secret: Sy301+cS1kWLq3eTr8dh+6U+le3MOfJfB9abbvgdfYg=
  lifetime: 30m
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update